# PyCal - Python web calendar
#
# Copyright (C) 2004-2006 Ray Osborn
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

"""PyCal configuration settings.

This file contains all the information defining the calendar
and the web server. This should be edited before installing PyCal.
"""

import os

# The full name of the calendar
calendarName = "<SiteName> Calendar"

# Brief version of the calendar name.
# This is used in the titles and headers of various calendar web pages.
calendarAbbr = "<SiteAbbr>"

# The address used for calendar administration correspondence.
calendarEmail = "<SiteEmail>"

# Calendar signature to be put at the end of all automatically generated
# email messages from 'calendarEmail'.
# The default substitutes the already initialized values of the full
# calendar name, abbreviation, and email address, 
# e.g.
# --
# Neutron Scattering Calendar
# Neutron Administration: <neutron-admin@anl.gov>
calendarSignature = "%s Calendar: <%s>" % (calendarAbbr, calendarEmail)

# The SMTP server and the "From" address used to send email.
# The SMTP email address should be the same as "calendarEmail" to avoid
# confusion by people replying to automated emails.  However, some SMTP 
# servers won't allow non-local names (e.g. aliases) so we provide this 
# as an option.  Do not edit either of these unless you are sure you have to.
SMTPserver = "localhost"
SMTPemail = calendarEmail

# HTML header to be used on every web page generated by PyCal scripts.
# This should be valid HTML code that is inserted after the <body> statement 
# but before the first <h1> page header.  Since it will be loaded with every
# page, this should not be large or take a long time to load.  This header
# is also used to initialize the non-generated HTML pages containing 
# publication instructions. You are free to edit these and replace the 
# headers with something more substantial since they will not be regenerated
# unless you reinstall the PyCal system. 
calendarHeader =  ''

# HTML footer to be used on every web page generated by PyCal scripts.
# This should be valid HTML code that is inserted before the </body> 
# statement. See the general comments above for calendarHeader.
# If no footer is specified here, a generic one will be used.
calendarFooter = ''

# Home directory of the calendar, specified as a subdirectory of 'rootDir'  
# For security reasons, this should not be accessible from the web site.
rootDir = "/path/to/root/"
homeDir = os.path.join(rootDir, "calendar")

# Directory and URL of the calendar web page.
webDir = "/path/to/www/calendar/"
webURL = "http://www.site.org/calendar"

# URL of the home page of the web site.  This is the page that the "up" arrow
# links to in the year view of the calendar.  
homeURL = "http://www.site.org"

# The CGI directory containing the PyCal scripts.
# If you are running more than one calendar on a single site, put
# this in a subdirectory of the default CGI directory
cgiDir = "/path/to/cgi-bin/calendar/"

# The CGI URL should be an absolute path with respect to the root URL
cgiURL = "http://www.site.org/cgi-bin/calendar"

# The backup directory is where backups of the calendar events are stored.
backupDir = os.path.join(rootDir, "backups")

# The length of time in seconds before clearing a stale file lock
lockWait = 60

# The maximum number of event log entries to be stored at any time.  When the
# logs database exceeds this size, the oldest entries are purged whenever a 
# new entry is added.
logSize = 100


